"""empty message

Revision ID: 1f4dd1c94c08
Revises: 2f2fac56ee07
Create Date: 2017-02-05 00:50:22.435233

"""

# revision identifiers, used by Alembic.
revision = '1f4dd1c94c08'
down_revision = '2f2fac56ee07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'username')
    ### end Alembic commands ###
