"""empty message

Revision ID: 2f2fac56ee07
Revises: 71998ec961ff
Create Date: 2017-02-04 16:11:07.221901

"""

# revision identifiers, used by Alembic.
revision = '2f2fac56ee07'
down_revision = '71998ec961ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
