"""empty message

Revision ID: 4a80051f45c5
Revises: 9b70c9877662
Create Date: 2017-02-11 20:02:28.562135

"""

# revision identifiers, used by Alembic.
revision = '4a80051f45c5'
down_revision = '9b70c9877662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kropotkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
#    op.drop_table('spatial_ref_sys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('kropotkin')
    ### end Alembic commands ###
