"""empty message

Revision ID: 71998ec961ff
Revises: d68f1b37db62
Create Date: 2017-02-03 10:28:46.046269

"""

# revision identifiers, used by Alembic.
revision = '71998ec961ff'
down_revision = 'd68f1b37db62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
