"""empty message

Revision ID: a4fcbc9bf7ec
Revises: 251e8aae0dde
Create Date: 2017-02-07 15:37:23.586550

"""

# revision identifiers, used by Alembic.
revision = 'a4fcbc9bf7ec'
down_revision = '251e8aae0dde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('profile', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('schedule', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'profile', ['profile'], ['id'])
    op.create_foreign_key(None, 'user', 'schedule', ['schedule'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'schedule')
    op.drop_column('user', 'profile')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'expiration_date')
    op.drop_column('user', 'created_on')
    ### end Alembic commands ###
