"""empty message

Revision ID: d68f1b37db62
Revises: d65adb569463
Create Date: 2017-02-01 17:42:19.679936

"""

# revision identifiers, used by Alembic.
revision = 'd68f1b37db62'
down_revision = 'd65adb569463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing_tag_association', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint('thing_tag_association_subtype_id_fkey', 'thing_tag_association', type_='foreignkey')
    op.create_foreign_key(None, 'thing_tag_association', 'tag', ['tag_id'], ['id'])
    op.drop_column('thing_tag_association', 'subtype_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing_tag_association', sa.Column('subtype_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'thing_tag_association', type_='foreignkey')
    op.create_foreign_key('thing_tag_association_subtype_id_fkey', 'thing_tag_association', 'subtype', ['subtype_id'], ['id'])
    op.drop_column('thing_tag_association', 'tag_id')
    ### end Alembic commands ###
