"""empty message

Revision ID: f4fabea1686d
Revises: a4fcbc9bf7ec
Create Date: 2017-02-10 12:09:05.429424

"""

# revision identifiers, used by Alembic.
revision = 'f4fabea1686d'
down_revision = 'a4fcbc9bf7ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'latitude')
    op.drop_column('space', 'longitude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('space', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    ### end Alembic commands ###
