export const SHAREABLES_ALL_REQUEST = 'SHAREABLES_ALL_REQUEST';
export const SHAREABLES_ALL_REQUEST_SUCCESS = 'SHAREABLES_ALL_REQUEST_SUCCESS';
export const SHAREABLES_ALL_REQUEST_ERROR = 'SHAREABLES_ALL_REQUEST_ERROR';

export const SHAREABLE_SINGLE_REQUEST = 'SHAREABLE_SINGLE_REQUEST';
export const SHAREABLE_SINGLE_REQUEST_SUCCESS = 'SHAREABLE_SINGLE_REQUEST_SUCCESS';
export const SHAREABLE_SINGLE_REQUEST_ERROR = 'SHAREABLE_SINGLE_REQUEST_ERROR';
