export const SHAREABLES_ALL_REQUEST = 'SHAREABLES_ALL_REQUEST';
export const SHAREABLES_ALL_REQUEST_SUCCESS = 'SHAREABLES_ALL_REQUEST_SUCCESS';
export const SHAREABLES_ALL_REQUEST_ERROR = 'SHAREABLES_ALL_REQUEST_ERROR';

