export const REQUEST_SHAREABLES = 'REQUEST_SHAREABLES';
export const REQUEST_SHAREABLES_SUCCESS = 'REQUEST_SHAREABLES_SUCCESS';
export const REQUEST_SHAREABLES_ERROR = 'REQUEST_SHAREABLES_ERROR';

export const ADD_SHAREABLE = 'ADD_SHAREABLE';
export const ADD_SHAREABLE_SUCCESS = 'ADD_SHAREABLE_SUCCESS';
export const ADD_SHAREABLE_ERROR = 'ADD_SHAREABLE_ERROR';

export const DELETE_SHAREABLE = 'DELETE_SHAREABLE';
export const DELETE_SHAREABLE_SUCCESS = 'DELETE_SHAREABLE_SUCCESS';
export const DELETE_SHAREABLE_ERROR = 'DELETE_SHAREABLE_ERROR';

export const EDIT_SHAREABLE = 'EDIT_SHAREABLE';
export const EDIT_SHAREABLE_SUCCESS = 'EDIT_SHAREABLE_SUCCESS';
export const EDIT_SHAREABLE_ERROR = 'EDIT_SHAREABLE_ERROR';

export const UPDATE_SHAREABLE = 'UPDATE_SHAREABLES';
export const UPDATE_SHAREABLE_SUCCESS = 'UPDATE_SHAREABLES_SUCCESS';
export const UPDATE_SHAREABLE_ERROR = 'UPDATE_SHAREABLES_ERROR';

export const LOAD_SHAREABLES = 'LOAD_SHAREABLES';
export const LOAD_SHAREABLES_SUCCESS = 'LOAD_SHAREABLES_SUCCESS';
export const LOAD_SHAREABLES_ERROR = 'LOAD_SHAREABLES_ERROR';


export const CREATE_SHAREABLE = 'CREATE_SHAREABLES';
export const CREATE_SHAREABLE_SUCCESS = 'CREATE_SHAREABLES_SUCCESS';
export const CREATE_SHAREABLE_ERROR = 'CREATE_SHAREABLES_ERROR';


export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
