"""empty message

Revision ID: 1a98a3dadb28
Revises: None
Create Date: 2016-11-02 12:44:08.376099

"""

# revision identifiers, used by Alembic.
revision = '1a98a3dadb28'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('additional_info', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('additional_info'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=True)
    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longditude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('canonical_address', sa.String(length=560), nullable=True),
    sa.Column('alternate_names', postgresql.ARRAY(Text()), nullable=True),
    sa.Column('notes', sa.String(length=2054), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descriptionHow', sa.String(length=140), nullable=True),
    sa.Column('descriptionWhat', sa.String(length=140), nullable=True),
    sa.Column('tags', postgresql.ARRAY(Text()), nullable=False),
    sa.Column('type', app.models.shareable_models.ShareableType(), nullable=True),
    sa.Column('subtypes', postgresql.ARRAY(Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shareable_subtype', 'thing', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('rrules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vevent_id', sa.Integer(), nullable=False),
    sa.Column('privacyLevel', sa.String(length=12), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=<built-in function max>), nullable=True),
    sa.Column('dtStart', sa.DateTime(), nullable=False),
    sa.Column('dtEnd', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('geoLat', sa.Float(), nullable=True),
    sa.Column('geoLng', sa.Float(), nullable=True),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=<built-in function max>), nullable=True),
    sa.Column('organizerCN', sa.String(length=50), nullable=True),
    sa.Column('organizerMailTo', sa.String(length=100), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('summary', sa.String(length=75), nullable=True),
    sa.Column('transparent', sa.Boolean(), nullable=False),
    sa.Column('freq', sa.String(length=8), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('bySecond', sa.String(length=170), nullable=True),
    sa.Column('byMinute', sa.String(length=170), nullable=True),
    sa.Column('byHour', sa.String(length=61), nullable=True),
    sa.Column('byDay', sa.String(length=35), nullable=True),
    sa.Column('byMonthDay', sa.String(length=200), nullable=True),
    sa.Column('byYearDay', sa.String(length=3078), nullable=True),
    sa.Column('byWeekNo', sa.String(length=353), nullable=True),
    sa.Column('byMonth', sa.String(length=29), nullable=True),
    sa.Column('wkSt', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['vevent_id'], ['vevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2054), nullable=True),
    sa.ForeignKeyConstraint(['calendar'], ['vevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guttersnipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['schedule'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=2054), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['guttersnipe.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['guttersnipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('blocker_id', sa.Integer(), nullable=True),
    sa.Column('blocked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['guttersnipe.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['guttersnipe.id'], )
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('shareable', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=2054), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['guttersnipe.id'], ),
    sa.ForeignKeyConstraint(['shareable'], ['guttersnipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shareable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('number_ratings', sa.Integer(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing_tag_join',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('thing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['shareable.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing_tag_join')
    op.drop_table('shareable')
    op.drop_table('comment')
    op.drop_table('followers')
    op.drop_table('messages')
    op.drop_table('guttersnipe')
    op.drop_table('time')
    op.drop_table('rrules')
    op.drop_index('ix_shareable_subtype', table_name='thing')
    op.drop_table('thing')
    op.drop_table('tag')
    op.drop_table('vevent')
    op.drop_table('schedule')
    op.drop_table('space')
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_table('profile')
    ### end Alembic commands ###
