export const KROPOTKIN_SINGLE_REQUEST = 'KROPOTKIN_SINGLE_REQUEST';
export const KROPOTKIN_SINGLE_REQUEST_SUCCESS = 'KROPOTKIN_SINGLE_REQUEST_SUCCESS';
export const KROPOTKIN_SINGLE_REQUEST_ERROR = 'KROPOTKIN_SINGLE_REQUEST_ERROR';
