export const SET_CATEGORY = "SET_CATEGORY";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";

export const SET_CENTER = "SET_CENTER";
export const STORE_BROWSER_LOCATION = "STORE_BROWSER_LOCATION";
export const SET_RADIUS = "SET_RADIUS";

export const SHAREABLE_LIST_REQUEST = "SHAREABLE_LIST_REQUEST";
export const SHAREABLE_LIST_SUCCESS = "SHAREABLE_LIST_SUCCESS";
export const SHAREABLE_LIST_FAILURE = "SHAREABLE_LIST_FAILURE";

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE";


export const SHAREABLE_SINGLE_REQUEST = "SHAREABLE_SINGLE_REQUEST";
export const SHAREABLE_SINGLE_SUCCESS = "SHAREABLE_SINGLE_SUCCESS";
export const SHAREABLE_SINGLE_FAILURE = "SHAREABLE_SINGLE_FAILURE";

export const SHAREABLES_SET_CURRENT = "SHAREABLES_SET_CURRENT";

export const KROPOTKIN_PARAGRAPH_REQUEST = "KROPOTKIN_PARAGRAPH_REQUEST";
export const KROPOTKIN_PARAGRAPH_SUCCESS = "KROPOTKIN_PARAGRAPH_SUCCESS";
export const KROPOTKIN_PARAGRAPH_FAILURE = "KROPOTKIN_PARAGRAPH_FAILURE";
