export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SHAREABLE_LIST_REQUEST = 'SHAREABLE_LIST_REQUEST';
export const SHAREABLE_LIST_SUCCESS = 'SHAREABLE_LIST_SUCCESS';
export const SHAREABLE_LIST_FAILURE = 'SHAREABLE_LIST_FAILURE';
export const SHAREABLE_FULL_REQUEST = 'SHAREABLE_FULL_REQUEST';
export const SHAREABLE_FULL_SUCCESS = 'SHAREABLE_FULL_SUCCESS';
export const SHAREABLE_FULL_FAILURE = 'SHAREABLE_FULL_FAILURE';
export const USER_RECORD_REQUEST = 'USER_RECORD_REQUEST';
export const USER_RECORD_SUCCESS = 'USER_RECORD_SUCCESS';
export const USER_RECORD_FAILURE = 'USER_RECORD_FAILURE';
export const KROTKIN_PARAGRAPH_REQUEST = 'KROTKIN_PARAGRAPH_REQUEST';
export const KROTKIN_PARAGRAPH_SUCCESS = 'KROTKIN_PARAGRAPH_SUCCESS';
export const KROTKIN_PARAGRAPH_FAILURE = 'KROTKIN_PARAGRAPH_FAILURE';
export const STORE_BROWSER_LOCATION = 'STORE_BROWSER_LOCATION';


export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const KROPOTKIN_SINGLE_REQUEST = 'KROPOTKIN_SINGLE_REQUEST';
export const KROPOTKIN_SINGLE_REQUEST_SUCCESS = 'KROPOTKIN_SINGLE_REQUEST_SUCCESS';
export const KROPOTKIN_SINGLE_REQUEST_ERROR = 'KROPOTKIN_SINGLE_REQUEST_ERROR';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS';

export const SHAREABLES_ALL_REQUEST = 'SHAREABLES_ALL_REQUEST';
export const SHAREABLES_ALL_REQUEST_SUCCESS = 'SHAREABLES_ALL_REQUEST_SUCCESS';
export const SHAREABLES_ALL_REQUEST_ERROR = 'SHAREABLES_ALL_REQUEST_ERROR';

export const SHAREABLE_SINGLE_REQUEST = 'SHAREABLE_SINGLE_REQUEST';
export const SHAREABLE_SINGLE_REQUEST_SUCCESS = 'SHAREABLE_SINGLE_REQUEST_SUCCESS';
export const SHAREABLE_SINGLE_REQUEST_ERROR = 'SHAREABLE_SINGLE_REQUEST_ERROR';

export const SHAREABLES_SET_CURRENT = 'SHAREABLES_SET_CURRENT';

export const SHAREABLES_CREATE_REQUEST = 'SHAREABLES_CREATE_REQUEST';
export const SHAREABLES_CREATE_REQUEST_SUCCESS = 'SHAREABLES_CREATE_REQUEST_SUCCESS';
export const SHAREABLES_CREATE_REQUEST_ERROR = 'SHAREABLES_CREATE_REQUEST_ERROR';

export const SHAREABLE_CATEGORIZATION_REQUEST = 'SHAREABLE_CATEGORIZATION_REQUEST';
export const SHAREABLE_CATEGORIZATIONS_SUCCESS = 'SHAREABLE_CATEGORIZATIONS_SUCCESS';

export const SHAREABLES_SEARCH_REQUEST = 'SHAREABLES_SEARCH_REQUEST';
export const SHAREABLES_SEARCH_REQUEST_SUCCESS = 'SHAREABLES_SEARCH_REQUEST_SUCCESS';
export const SHAREABLES_SEARCH_REQUEST_ERROR = 'SHAREABLES_SEARCH_REQUEST_ERROR';
