export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS';

export const SHAREABLES_ALL_REQUEST = 'SHAREABLES_ALL_REQUEST';
export const SHAREABLES_ALL_REQUEST_SUCCESS = 'SHAREABLES_ALL_REQUEST_SUCCESS';
export const SHAREABLES_ALL_REQUEST_ERROR = 'SHAREABLES_ALL_REQUEST_ERROR';

export const SHAREABLE_SINGLE_REQUEST = 'SHAREABLE_SINGLE_REQUEST';
export const SHAREABLE_SINGLE_REQUEST_SUCCESS = 'SHAREABLE_SINGLE_REQUEST_SUCCESS';
export const SHAREABLE_SINGLE_REQUEST_ERROR = 'SHAREABLE_SINGLE_REQUEST_ERROR';

export const SHAREABLES_SET_CURRENT = 'SHAREABLES_SET_CURRENT';

export const SHAREABLES_CREATE_REQUEST = 'SHAREABLES_CREATE_REQUEST';
export const SHAREABLES_CREATE_REQUEST_SUCCESS = 'SHAREABLES_CREATE_REQUEST_SUCCESS';
export const SHAREABLES_CREATE_REQUEST_ERROR = 'SHAREABLES_CREATE_REQUEST_ERROR';

export const SHAREABLE_CATEGORIZATION_REQUEST = 'SHAREABLE_CATEGORIZATION_REQUEST';
export const SHAREABLE_CATEGORIZATIONS_SUCCESS = 'SHAREABLE_CATEGORIZATIONS_SUCCESS';

export const SHAREABLES_SEARCH_REQUEST = 'SHAREABLES_SEARCH_REQUEST';
export const SHAREABLES_SEARCH_REQUEST_SUCCESS = 'SHAREABLES_SEARCH_REQUEST_SUCCESS';
export const SHAREABLES_SEARCH_REQUEST_ERROR = 'SHAREABLES_SEARCH_REQUEST_ERROR';

